# https://pre-commit.com/
# https://pre-commit.com/hooks.html
# https://pre-commit.com/#pre-commit-configyaml---top-level
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-symlinks
      - id: pretty-format-json
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-vcs-permalinks
      # - id: check-added-large-files
      #   args: ["--maxkb=20000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # - repo: https://github.com/boidolr/pre-commit-images
  #   rev: v1.8.4
  #   hooks:
  #     - id: optimize-jpg
  #     - id: optimize-png

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/crate-ci/typos
    rev: v1.33.1
    hooks:
      - id: typos

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args:
          ["--maxlevel", "2", "--github", "--title", "\n## Table of Contents"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        exclude: ".github/workflows"

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
