#!/usr/bin/env sh

echo "running pre-commit hook..."

set -e

# echo "TODO: add linting and formatting checks here"
# gh act push  # this makes commiting slow, try doing it async on push for a while

echo "pre-commit hook completed successfully."