#!/usr/bin/env sh

echo "running pre-commit hook..."

set -e

# Check if ruff is installed
if ! command -v ruff > /dev/null; then
  echo "Ruff is not installed. Installing ruff..."
  python -m pip install --user ruff
fi

# Run ruff for linting
echo "Running ruff for linting..."
python -m ruff check .

# Run ruff for formatting
echo "Running ruff for formatting..."
python -m ruff format --check .

# echo "TODO: add linting and formatting checks here"
gh act push

echo "pre-commit hook completed successfully."