#!/usr/bin/env sh
# pre commit hook for linting, formatting, and running tests

printf "\033[33mpre-commit hook \033[0m\n"

set -e

# TODO: remove if commenting this out doesn't break anything
# Check if ruff is installed
# if ! command -v ruff >/dev/null; then
# 	echo "Ruff is not installed. Installing ruff..."
# 	python -m pip install ruff
# fi

printf "\033[35mruff check . \033[0m\n"

ruff check .

printf "\033[35mruff format . \033[0m\n"

ruff format .

printf "\033[35mrunning tests \033[0m\n"

gh act push

printf "\033[32mpre-commit hook complete \033[0m\n"
