#!/usr/bin/env sh
# pre commit hook for linting, formatting, and running tests

set -e

printf "\033[33mpre-push hook \033[0m\n"

# ensure the pre-commit uses the correct python environment
poetry env use python3
eval $(poetry env activate | sed 's/source/./')

printf "\033[35mrunning tests \033[0m\n"
# see [nektosact.com/usage](https://nektosact.com/usage)
gh act push

printf "\033[32mpre-commit hook complete \033[0m\n"
