name: Blender Tests

on:
  push:
    branches: [main] # Or your default branch
  pull_request:
    branches: [main] # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Adjust if your project uses a different version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poethepoet  # For running 'poe test'
          # Assuming requirements.txt contains other necessary Python packages
          # If not, add them here, e.g., pip install coverage Pillow ffmpeg-python
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Blender
        run: echo "installing blender..." && sudo apt-get update && sudo apt-get install -y blender && echo "Blender installed successfully"

      - name: Install butils for Blender (custom setup)
        run: python -m butils install

      - name: Verify Blender installation
        run: blender --version

      - name: Run tests with poethepoet
        # The 'poe test' command from pyproject.toml is:
        # blender --background --python tests/run_tests.py -- --no-buffer --verbosity 2
        # This command should now use the Blender from the PATH
        run: poe test
        # To include coverage, ensure 'poe test' calls tests/run_tests.py with --coverage,
        # or add a separate step/task:
        # run: blender --background --python tests/run_tests.py -- --coverage --no-buffer --verbosity 2
